; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:m5stack-core2]
platform = espressif32
framework = arduino
board = m5stack-core2
monitor_speed = 115200
monitor_filters = esp32_exception_decoder  ; For backtrace decoding
build_flags =
	; -D SIMULATOR_OR_DEBUG
    -DPRESSURE_SENSOR_DEBUG=1
    -DCORE_DEBUG_LEVEL=0
    -DARDUINO_RUNNING_CORE=1
    -DARDUINO_EVENT_RUNNING_CORE=1
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
    -mfix-esp32-psram-cache-strategy=memw
    -Iinclude/fonts/
    -DOFR_FS_PRESET=OFR::spiffs
upload_speed = 1500000
lib_deps =
    m5stack/M5Unified@0.2.1
    m5stack/M5GFX@0.2.0
build_src_filter =
    +<*>
    -<simulator_main.cpp>
    -<ui/simulator_backend.cpp>
extra_scripts = post:package_script.py
check_tool = clangtidy
board_upload.flash_size = 16MB  ; Ensure enough space
board_build.partitions = default_16MB.csv  ; Use a partition table with SPIFFS

[env:native]
platform = native
test_framework = unity
test_build_src = yes
build_flags =
    -Isrc
build_src_filter =
    -<*>
    +<ble/BleProtocol.cpp>
    +<ble_scale/LfSmartScaleProtocol.cpp>
    +<ble_scale/ScaleTypes.cpp>
test_filter =
    test_ble_protocol
    test_scale_protocol

; [env:simulator]
; platform = native
; build_flags =
;     -D SIMULATOR
;     -D SIMULATOR_OR_DEBUG
;     !pkg-config --cflags --libs sdl2
;     !pkg-config --cflags --libs SDL2_ttf
;     -I.
;     -Iinclude/fonts/
;     -Wno-narrowing
; build_src_filter =
;     -<*>
;     +<simulator_main.cpp>
;     +<ui/simulator_backend.cpp>
;     +<ui/ui.cpp>
;     +<ui/ui.h>
;     +<ui/canvas_wrapper.h>
;     +<constants.h>
;     +<pressure_sensor/pressure_sensor.h>
;     +<pressure_sensor/pressure_sensor.cpp>
;     +<SimulatorArduino.h>
;     +<SimulatorArduino.cpp>
; check_tool = clangtidy
; ; extra_scripts = pre:copy_fonts.py

[package]
name = mXcoffee
version = 0.0.3
description = mXcoffee firmware
author = Victor Shcherbakov
url = https://github.com/focusshifter/mXcoffee

[platformio]
default_envs = m5stack-core2
