name: PlatformIO Build

on:
  push:
    branches: [ "main" ]
    tags:
      - 'v*'
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Cache PlatformIO Dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.platformio/.cache
        key: ${{ runner.os }}-pio-${{ hashFiles('**/platformio.ini') }}
        restore-keys: |
          ${{ runner.os }}-pio-

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        
    - name: Install PlatformIO Core
      run: |
        python -m pip install --upgrade pip
        pip install platformio

    - name: Build firmware
      run: pio run -e m5stack-core2

    - name: Upload firmware artifact
      uses: actions/upload-artifact@v4
      with:
        name: firmware
        path: .pio/build/m5stack-core2/firmware.bin

    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v2
      with:
        files: .pio/build/m5stack-core2/firmware.bin
        generate_release_notes: true
